text = { 
    (!("<") ~ ANY)+ 
}
tag_name = {
    (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")*
}
attribute_name = {
    (ASCII_ALPHA | ("_" ~ ASCII_ALPHANUMERIC)) ~ (ASCII_ALPHANUMERIC | "_" | "-")*
}
attribute_value = {
    (!("\"" | "\'") ~ (ANY))+
}
attribute = {
    attribute_name  ~ (" ")* ~ "=" ~ (" ")* ~ "\"" ~ (attribute_value | "") ~ "\""
}
opening_tag = {
    "<" ~ tag_name ~ (" ")* ~ (attribute ~ (" ")*)* ~ ">"
}
closing_tag = {
    "</" ~ tag_name ~ (" ")* ~ ">"
}